tasks:
  - task_id: incident_55_task_91
    title: incident_55_task_91
    description: "During the same time frame, there was an attempt where a Windows executable file was renamed and launched. Can you identify the system account that was used to perform these actions?"

    inherit_shared: true

    initial_context:
      incident_context: "On 2024-07-10, during a suspected unauthorized activity, the account `gsmith@niseko.alpineskihouse.co` read the DKM key of ADFS object id 4cac49d3-29d3-407e-8c9b-b7ebb21541b2. Additionally, a suspicious LDAP query was detected that might indicate an attempt to steal ADFS private keys."
      question: "During the same time frame, there was an attempt where a Windows executable file was renamed and launched. Can you identify the system account that was used to perform these actions?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "SYSTEM"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The account `gsmith` read the DKM key of ADFS with object id `4cac49d3-29d3-407e-8c9b-b7ebb21541b2`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A suspicious LDAP query was launched, potentially attempting to steal ADFS private keys, with the process `iy2orr1e.rrg.exe`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "A Windows executable file, renamed as `iy2orr1e.rrg.exe`, was launched by the `SYSTEM` account to perform potentially malicious activities."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_92
    title: incident_55_task_92
    description: "It was later observed that a phishing email was sent internally, likely from a compromised user account. Can you identify the email address of the user who sent the phishing email?"

    inherit_shared: true

    initial_context:
      incident_context: "A process initiated a suspicious sequence of exploration activities by calling a set of windows commands. These commands are often used by attackers to identify valuable assets and coordinate lateral movement after compromising a machine. During this incident, multiple processes including `whoami.exe` and `svchost.exe` were run, and the device involved is `mb-winclient` associated with the account `pwilson` and IP address `72.5.72.208`."
      question: "It was later observed that a phishing email was sent internally, likely from a compromised user account. Can you identify the email address of the user who sent the phishing email?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "Nina Sullivan@vnevado.alpineskihouse.co"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A suspicious sequence of exploration activities was performed by an account with SID `S-1-5-21-561436748-3867387497-1732241745-3701`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "An internal phishing campaign was conducted by a user with email `Nina Sullivan@vnevado.alpineskihouse.co`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_93
    title: incident_55_task_93
    description: "Given this context, a related alert was triggered due to suspicious remote activity. Can you identify the name of the file that was involved in this suspicious remote activity?"

    inherit_shared: true

    initial_context:
      incident_context: "During a security investigation, a suspicious system hardware discovery was identified, showing that a known tool or technique was used to gather information on the device. An attacker might be attempting to gather information about the target device or network for subsequent attacks. The device in question is `mb-winclient`, and there was evidence of potentially malicious processes such as `powershell.exe` and `svchost.exe` being executed."
      question: "Given this context, a related alert was triggered due to suspicious remote activity. Can you identify the name of the file that was involved in this suspicious remote activity?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "cmd.exe"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "There was a suspicious system hardware discovery using `powershell.exe`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "Suspicious remote activity involved the execution of `cmd.exe` on this machine."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_94
    title: incident_55_task_94
    description: "In relation to the internal phishing campaign, can you provide the Azure AD UserID associated with the compromised account?"

    inherit_shared: true

    initial_context:
      incident_context: "Our security monitoring system detected a potentially malicious URL click activity by the mailbox `bjenkins@niseko.alpineskihouse.co`. This incident may be connected to an internal phishing campaign where a user sent phishing emails to recipients within the organization, suggesting a possible compromise of the user account in an attempt by an attacker to move laterally inside the organization."
      question: "In relation to the internal phishing campaign, can you provide the Azure AD UserID associated with the compromised account?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "28058d92-fc24-4869-9231-6546a34b00f2"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A user with AadUserId `a2d0f7c2-b0a0-43bd-bce0-27d8ae3be4d0` clicked on a link that was found to be malicious."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "Another user with AadUserId `28058d92-fc24-4869-9231-6546a34b00f2` was observed to have sent phishing emails within the organization, indicating a potential account compromise and lateral movement attempt."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_95
    title: incident_55_task_95
    description: "In a related alert within the same incident, it mentions a suspicious sequence of exploration activities involving a different account. Can you provide the name of the account involved in this suspicious exploration?"

    inherit_shared: true

    initial_context:
      incident_context: "Related alerts might indicate further compromise actions."
      question: "In a related alert within the same incident, it mentions a suspicious sequence of exploration activities involving a different account. Can you provide the name of the account involved in this suspicious exploration?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "bjenkins"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The user Luciano Herrera (pwilson@niseko.alpineskihouse.co) added an unusual credential of type Password to the application SimulandApp, which may indicate that the account with AadUserId `2de70991-2799-4a95-b734-8e3df3a50118` has been compromised."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "The account with name `bjenkins` was involved in a suspicious sequence of exploration activities, executing a set of windows commands that could be used for identifying valuable assets and coordinating lateral movements after compromising a machine."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_96
    title: incident_55_task_96
    description: "What is the name of the user account associated with the malicious PowerShell Cmdlet invocation?"

    inherit_shared: true

    initial_context:
      incident_context: "A system program `services.exe` was registered as a service on 2024-07-04 which could indicate a malicious intent to establish persistence or gain system privileges. Following this, there was a Suspicious Task Scheduler activity involving a process that might indicate an attempt to launch malicious code automatically and establish persistence. The series of activities also included a malicious PowerShell Cmdlet invocation linked to potential credential theft, exploitation, network reconnaissance or code injection."
      question: "What is the name of the user account associated with the malicious PowerShell Cmdlet invocation?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "bjenkins"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A suspicious service was registered on host `mb-adfs`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "The process `powershell.exe` used Task Scheduler to create, modify, or delete a task, which is indicative of potential malicious activity."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "The user account `bjenkins` invoked a malicious PowerShell Cmdlet on the machine."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_97
    title: incident_55_task_97
    description: "What is the hostname of the device that sent the replication request in the suspected DCSync attack?"

    inherit_shared: true

    initial_context:
      incident_context: "A security incident involving a suspicious sequence of exploration activities involving various windows commands was observed. One of the commands executed was associated with the process `iy2orr1e.rrg.exe` on host `mb-adfs`. This activity may indicate an attacker identifying valuable assets and preparing to move laterally after compromising the machine. Following this, a malicious PowerShell Cmdlet was invoked on the machine, which could be linked to credential theft, network reconnaissance, or code injection. Later, a suspected DCSync attack was detected, where Luciano Herrera (CIO) on an unknown host sent a replication request to an entity. The last event in the sequence was that the device `MB-DC1` read the DKM key of an ADFS object."
      question: "What is the hostname of the device that sent the replication request in the suspected DCSync attack?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "MB-WINCLIENT"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A suspicious sequence of exploration activities was conducted via the process `powershell.exe`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A malicious PowerShell Cmdlet was invoked by the user with SID `S-1-5-21-551436448-9871687716-9837441745-1903`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "Luciano Herrera (CIO) on the host `MB-WINCLIENT` sent a replication request to the host `MB-DC1`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_4
        title: Checkpoint 4
        description: "The host `MB-DC1` then read the DKM key of ADFS object id `4cac49d3-29d3-407e-8c9b-b7ebb21541b2`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_98
    title: incident_55_task_98
    description: "During this multi-stage incident, suspicious system hardware discovery activities were also observed. Can you identify the account name used to gather information about the target device?"

    inherit_shared: true

    initial_context:
      incident_context: "A suspicious service registration was observed where `services.exe` was registered as a service, potentially indicating malicious intent. An ongoing hands-on-keyboard attack was also detected involving the Impacket toolkit, used to connect to other hosts, explore network shares, and execute commands."
      question: "During this multi-stage incident, suspicious system hardware discovery activities were also observed. Can you identify the account name used to gather information about the target device?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "pwilson"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The system program was registered as a service on host `mb-adfs`, indicating a possible attempt at persistence or privilege escalation."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "Suspicious execution of a command via Impacket toolkit using `powershell.exe` was observed, suggesting an ongoing hands-on-keyboard attack attempting lateral movement across the network."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "Account `pwilson` was involved in a suspicious system hardware discovery activity, where a known tool or technique was used to gather information about the device or network for potential future attacks."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_99
    title: incident_55_task_99
    description: "What is the name of the account involved in reading the DKM key of the ADFS object?"

    inherit_shared: true

    initial_context:
      incident_context: "A suspicious service creation was detected on host `MB-ADFS` where a user created a service named `DDLOXJDSQSNGMUKKFUXQ` to execute potentially malicious commands. This activity might be part of a larger security incident involving the same host."
      question: "What is the name of the account involved in reading the DKM key of the ADFS object?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "gsmith"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "User `gsmith` created a service named `DDLOXJDSQSNGMUKKFUXQ` to execute potentially malicious commands on `MB-ADFS`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "User `gsmith` read the DKM key of ADFS object id `4cac49d3-29d3-407e-8c9b-b7ebb21541b2`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_100
    title: incident_55_task_100
    description: "As we investigate this internal phishing campaign, can you identify the email address of the account involved in suspicious activities related to `Lucas Grey@niseko.alpineskihouse.co`?"

    inherit_shared: true

    initial_context:
      incident_context: "An internal phishing campaign was detected where a user sent phishing emails to recipients inside the organization. The user, Lucas Grey (Email: Lucas Grey@niseko.alpineskihouse.co), might have had their account compromised. This incident was flagged by Microsoft Defender for Office 365."
      question: "As we investigate this internal phishing campaign, can you identify the email address of the account involved in suspicious activities related to `Lucas Grey@niseko.alpineskihouse.co`?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "Nina Sullivan@vnevado.alpineskihouse.co"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The user with the email `Nina Sullivan@vnevado.alpineskihouse.co` was observed to have sent phishing emails to recipients inside the organization, indicating that the account might have been compromised."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
