tasks:
  - task_id: incident_55_task_11
    title: incident_55_task_11
    description: "In relation to this alert, there was an attempt to extract ADFS private keys using a suspicious LDAP query. Can you identify the name of the account that was involved in this attempt?"

    inherit_shared: true

    initial_context:
      incident_context: "As part of a suspicious sequence of exploration activities reported on 2024-07-04, a process executed a set of Windows commands like `powershell.exe` and `whoami.exe`. These specific commands are often used by attackers to identify valuable assets and coordinate lateral movement after compromising a machine."
      question: "In relation to this alert, there was an attempt to extract ADFS private keys using a suspicious LDAP query. Can you identify the name of the account that was involved in this attempt?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "gsmith"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "Suspicious activities were initiated by the user with SID `S-2-5-21-571436798-3864380397-1837441745-3206`, involving a set of windows commands."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A suspicious LDAP query was launched by the user account `gsmith`, indicating a possible attempt to extract ADFS private keys or lateral movement."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_12
    title: incident_55_task_12
    description: "Regarding the suspicious remote activity observed, which executable file was used during this activity?"

    inherit_shared: true

    initial_context:
      incident_context: "During a security incident investigation, it was observed that the account `gsmith@niseko.alpineskihouse.co` read the DKM key of an ADFS object with id 4cac49d3-29d3-407e-8c9b-b7ebb21541b2. This might indicate unauthorized accessing of sensitive AD FS information."
      question: "Regarding the suspicious remote activity observed, which executable file was used during this activity?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "powershell.exe"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The account `gsmith` read the DKM key of ADFS object id `4cac49d3-29d3-407e-8c9b-b7ebb21541b2`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "There was suspicious remote activity involving the file `powershell.exe`. This suggests possibly malicious attempts to initiate interactive sessions, modify files, pass WMI commands, create scheduled tasks, and other similar activities."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_13
    title: incident_55_task_13
    description: "During this period, it was detected that a user clicked on a potentially malicious URL. Can you identify the primary address of the mailbox associated with this user?"

    inherit_shared: true

    initial_context:
      incident_context: "A recent security incident involving an Ongoing hands-on-keyboard attack via the Impacket toolkit and suspicious system hardware discovery was detected. The Impacket tool was used to attempt lateral movement across the network. This was discovered on host `mb-adfs`, with processes like `lsass.exe` and `powershell.exe` being involved. The alerts indicate attempts to gather information about the target device or network for later attacks, possibly discovering hardware information. Additionally, a known technique was used to perform these malicious activities."
      question: "During this period, it was detected that a user clicked on a potentially malicious URL. Can you identify the primary address of the mailbox associated with this user?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "bjenkins@niseko.alpineskihouse.co"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A hands-on-keyboard attack via the Impacket toolkit was detected with the suspicious execution of `powershell.exe` on a device."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "Suspicious system hardware discovery was carried out by the account with SID `S-1-5-21-561436748-3867387497-1732241745-3701`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "The mailbox `bjenkins@niseko.alpineskihouse.co` had a user that clicked on a potentially malicious URL."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_14
    title: incident_55_task_14
    description: "Can you identify the SID of the account that executed the suspicious LDAP query?"

    inherit_shared: true

    initial_context:
      incident_context: "In a recent case of suspicious remote activity observed on a machine named `mb-adfs`, there were several processes involved including `lsass.exe`, `cmd.exe`, and `powershell.exe`. This activity was flagged due to the potential initiation of interactive sessions, modification of files, WMI commands, or creating scheduled tasks which could be malicious. The observed processes were linked with different Process IDs and timestamps."
      question: "Can you identify the SID of the account that executed the suspicious LDAP query?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "S-1-5-21-551436448-9871687716-9837441745-1903"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "Suspicious remote activity was initiated using `powershell.exe`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A suspect LDAP query was executed by an account with SID `S-1-5-21-551436448-9871687716-9837441745-1903`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_15
    title: incident_55_task_15
    description: "What is the process ID associated with the suspicious Task Scheduler activity?"

    inherit_shared: true

    initial_context:
      incident_context: "As part of a suspected attack, the account `gsmith@niseko.alpineskihouse.co` was reported to have read the DKM key of an AD FS (Active Directory Federation Services) object. Following this, there were a series of suspicious exploration activities involving a set of windows commands that could indicate coordinated lateral movement by attackers. This was followed by a process that engaged in suspicious Task Scheduler activity to create, modify, or delete a task. This might be an attempt to launch malicious code automatically and establish persistence. For further details, refer to the threat analytics report: https://security.microsoft.com/threatanalytics3/c9709a39-ac8d-493d-9a63-71da3ca1e745/analystreport."
      question: "What is the process ID associated with the suspicious Task Scheduler activity?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "4304"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The account `gsmith` read the DKM key of ADFS object id `4cac49d3-29d3-407e-8c9b-b7ebb21541b2`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "There was a suspicious sequence of exploration activities involving a process with filename `iy2orr1e.rrg.exe`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "A process involved in earlier malicious activity used Task Scheduler to create, modify, or delete a task with Process ID `4304` at `2024-07-02t09:48:23.4654342z`. The command line used was `schtasks.exe /create /ru niseko\\adfsadmin /rp toptc88coob3xvxtpbr8 /sc daily /tn run-exportadfstokensignincert.2024-07-02_09_48_23 /tr "
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_4
        title: Checkpoint 4
        description: "iy2orr1e.rrg.exe -windowstyle hidden -encodedcommand qwa6afwauwbjahiaaqbwahqacwbcaeuaeabwag8acgb0aeearabgafmavabvagsazqbuafmaaqbnag4aaqbuaemazqbyahqalgbwahmamqa="
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_5
        title: Checkpoint 5
        description: "/st 00:00:00 /f`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_16
    title: incident_55_task_16
    description: "What is the name of the process involved in the suspicious Task Scheduler activity?"

    inherit_shared: true

    initial_context:
      incident_context: "On 2024-07-04, suspicious remote activity was observed on a machine. This includes attempts to initiate interactive sessions, modify files, pass WMI commands, create scheduled tasks, and other potentially malicious activities from a remote machine."
      question: "What is the name of the process involved in the suspicious Task Scheduler activity?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "iy2orr1e.rrg.exe"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "There was suspicious remote activity observed on the host `mb-adfs`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A process with the file name `iy2orr1e.rrg.exe` used Task Scheduler to manipulate tasks, which could be an attempt to launch malicious code and establish persistence."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_17
    title: incident_55_task_17
    description: "Can you identify the sender of the email messages that contained the malicious URL and were removed after delivery?"

    inherit_shared: true

    initial_context:
      incident_context: "On 2024-07-10 at 11:24 AM, a suspicious service named DDLOXJDSQSNGMUKKFUXQ was created by gsmith on the host MB-ADFS, aiming to execute potentially malicious commands. This incident is part of a larger sequence of activities that included multiple exploration commands indicating potential lateral movement after compromising the machine. Following this, on 2024-07-09 at 11:49 AM, emails containing a malicious URL were delivered and subsequently removed, suggesting potential email-based threats."
      question: "Can you identify the sender of the email messages that contained the malicious URL and were removed after delivery?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "santiago@vnevado.alpineskihouse.co"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The account with AadUserId `ec3ec68b-fdeb-4fe4-9a29-acd445e1ccc5` created the service DDLOXJDSQSNGMUKKFUXQ to potentially execute malicious commands on MB-ADFS."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A process named `powershell.exe` executed a set of suspicious windows commands that could identify assets and coordinate lateral movement."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "The account with AadUserId `a2d0f7c2-b0a0-43bd-bce0-27d8ae3be4d0` was involved in the suspicious sequence of exploration activities."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_4
        title: Checkpoint 4
        description: "Emails containing malicious URLs that were sent by `santiago@vnevado.alpineskihouse.co` were delivered and later removed."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_18
    title: incident_55_task_18
    description: "Can you identify the email of the user who added credentials to the OAuth application SimulandApp?"

    inherit_shared: true

    initial_context:
      incident_context: "During the investigation of a suspicious sequence of exploration activities conducted on the host `mb-adfs` using processes like `iy2orr1e.rrg.exe` and `powershell.exe`, it was found that reconnaissance was performed via LDAP queries. Following these activities, an unusual addition of credentials to the OAuth application SimulandApp was observed."
      question: "Can you identify the email of the user who added credentials to the OAuth application SimulandApp?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "pwilson@niseko.alpineskihouse.co"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A suspicious sequence of exploration activities was conducted using `powershell.exe`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A suspect LDAP query was executed by the user with AadUserId `2de70991-2799-4a95-b734-8e3df3a50118`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "The user Luciano Herrera (pwilson@niseko.alpineskihouse.co) performed an unusual addition of credentials to the application SimulandApp (OAuthAppId `4d9476b8-6ae6-459b-a273-5837c15b5981`)."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_19
    title: incident_55_task_19
    description: "In the context of this reconnaissance activity, evidence of an ongoing hands-on-keyboard attack via Impacket was also observed. Can you identify the name of the user account involved in this Impacket activity?"

    inherit_shared: true

    initial_context:
      incident_context: "As part of a related suspicious LDAP query, the user account potentially involved in this activity is named `pwilson`, executed from the host `mb-winclient` with IP address `72.5.72.208` using powershell script `ldaprequest.ps1`."
      question: "In the context of this reconnaissance activity, evidence of an ongoing hands-on-keyboard attack via Impacket was also observed. Can you identify the name of the user account involved in this Impacket activity?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "gsmith"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A suspicious LDAP query was executed using `powershell.exe`, indicating potential reconnaissance activity."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "There was an ongoing hands-on-keyboard attack using the Impacket toolkit by an account with the name `gsmith`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_55_task_20
    title: incident_55_task_20
    description: "As part of this incident, there was a security alert indicating that a malicious URL was clicked on the device. Can you find the URL that was clicked?"

    inherit_shared: true

    initial_context:
      incident_context: "During a security incident on 2024-07-02, various suspicious activities were recorded on host `mb-adfs`. Specifically, multiple processes including `powershell.exe` and `iy2orr1e.rrg.exe` were launched with encoded commands indicating potential malicious intent. Additionally, there was a process injection alert, suggesting that malicious code had been injected into another process."
      question: "As part of this incident, there was a security alert indicating that a malicious URL was clicked on the device. Can you find the URL that was clicked?"

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "https://ym018491661.wittytree-b6f239d6.northeurope.azurecontainerapps.io/"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A renamed system executable `powershell.exe` was launched, likely indicating an attempt to avoid detection."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A process on the host with AadDeviceId `7661dfd4-218f-4016-8a87-66d68a7f098e` was injected with potentially malicious code."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "A malicious URL (`https://ym018491661.wittytree-b6f239d6.northeurope.azurecontainerapps.io/`) was clicked on the same device."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
