tasks:
  - task_id: incident_5_task_41
    title: incident_5_task_41
    description: During this investigation, a potentially compromised user account was
      identified. Can you provide the SID of the user account that may be operating
      with ransomware-like behavior?

    inherit_shared: true
    initial_context:
      incident_context: During a recent security investigation, it was found that a
        malicious credential theft tool `mimikatz.exe` was executed with the process
        ID 4464 on 2024-06-20 at 09:03:04.6442161, originating from IP address `107.224.99.179`.
        The command line included attempts to leverage credentials from the domain `vnevado.alpineskihouse.co`.
        This execution was flagged on 2024-07-04 at 22:35:03.869406+00:00 for its intent
        to dump user credentials. Subsequently, there was a lateral movement attempt
        to the jump server `Vnevado-jump` on 2024-07-10 at 11:24:45.260113+00:00.
      question: During this investigation, a potentially compromised user account was
        identified. Can you provide the SID of the user account that may be operating
        with ransomware-like behavior?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - S-1-5-21-1840191660-8534830288-125585561-1522
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: A known credential theft tool execution command was detected on the
        account with the name `tgs2z`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: Lateral movement to the jump server `Vnevado-jump` was performed
        from the IP address `99.83.111.100`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_3
      title: Checkpoint 3
      description: The account with SID `S-1-5-21-1840191660-8534830288-125585561-1522`
        was exhibiting ransomware-like behavior, impacting several devices.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_42
    title: incident_5_task_42
    description: Following this incident, 'CommandAndControl' malware was detected on
      another device during lateral movement. What is the AadDeviceId of this affected
      device?

    inherit_shared: true
    initial_context:
      incident_context: A security incident involving an attempt to access a Primary
        Refresh Token (PRT) was detected. The PRT is a key artifact of Azure AD authentication
        on various devices, including Windows 10. The incident involved a device with
        HostName `vnevado-win10s` and AadDeviceId `f5b847aa-8712-4bf6-b4f7-ed6cd89e1505`,
        where the process `browsercore.exe` (ProcessId `2676` created at `2024-06-20T09:10:59.867384Z`)
        was running. Attackers may use this to move laterally within the organization.
      question: Following this incident, 'CommandAndControl' malware was detected on
        another device during lateral movement. What is the AadDeviceId of this affected
        device?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - bc00e484-d0e5-4da4-9472-95568cccc07e
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: A possible attempt to access Primary Refresh Token (PRT) has been
        detected for the user with AadUserId `731adb71-b11c-4bbf-850b-57989b350e96`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: '''CommandAndControl'' malware was detected on the device with AadDeviceId
        `bc00e484-d0e5-4da4-9472-95568cccc07e`, indicating an attempt of lateral movement.'
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_43
    title: incident_5_task_43
    description: There was suspicious remote activity involving this malware incident.
      Can you identify the AadDeviceId of the host involved in this suspicious remote
      activity?

    inherit_shared: true
    initial_context:
      incident_context: A security incident was detected involving suspicious 'GenRansom'
        behavior on the host 'vnevado-win11t'. This malware can perform harmful actions
        and spread across machines. The active malware was found running or having persistence
        mechanisms in place, necessitating urgent precautionary measures. Following
        this, a system recovery setting tampering alert was observed on the device,
        where adversaries might be disabling recovery features using native Windows
        utilities.
      question: There was suspicious remote activity involving this malware incident.
        Can you identify the AadDeviceId of the host involved in this suspicious remote
        activity?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - bc00e484-d0e5-4da4-9472-95568cccc07e
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: Suspicious 'GenRansom' behavior was detected on device with AadDeviceId
        `e5799261-6720-4297-961e-bd9ca4275033`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: System recovery setting tampering was observed with the process `vssblatemp.exe`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_3
      title: Checkpoint 3
      description: Suspicious remote activity was detected on device with AadDeviceId
        `bc00e484-d0e5-4da4-9472-95568cccc07e`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_44
    title: incident_5_task_44
    description: In relation to the malicious credential theft tool execution detected
      in this multi-stage incident, can you identify the file name of the tool that
      was executed?

    inherit_shared: true
    initial_context:
      incident_context: A security incident regarding System recovery setting tampering
        and possible attempts to access Primary Refresh Token (PRT) was reported. Specifically,
        there was an attempt to disable system recovery features using `vssblatemp.exe`
        and `bcdedit` on the host `vnevado-win11u` with a user account having the SID
        `S-1-5-21-1840191660-8534830288-125585561-1522`. Notably, it included a potential
        access of PRTs, as mentioned in the Midnight Blizzard credential attacks Threat
        Analytics report.
      question: In relation to the malicious credential theft tool execution detected
        in this multi-stage incident, can you identify the file name of the tool that
        was executed?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - mimikatz.exe
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: The system recovery settings tampering was attempted by the user
        with AadUserId `731adb71-b11c-4bbf-850b-57989b350e96`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: An attempt to access Primary Refresh Token (PRT) was detected, associated
        with the process `browsercore.exe`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_3
      title: Checkpoint 3
      description: Another attempt to access Primary Refresh Token (PRT) was detected,
        originating from the IP address `107.224.99.179`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_4
      title: Checkpoint 4
      description: A malicious credential theft tool `mimikatz.exe` was executed.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_45
    title: incident_5_task_45
    description: Can you provide the command line details of the suspicious WMI process
      observed on the machine?

    inherit_shared: true
    initial_context:
      incident_context: A security incident involving the Manatee Tempest activity group
        was reported. This Russia-based cybercriminal group, which has been active since
        June 2014, is known for malware campaigns including the Dridex banking trojan.
        They often gain initial access through methods such as drive-by downloads and
        malvertising, facilitated by their partnership with Mustard Tempest. As part
        of this security incident, a suspicious WMI process creation was observed on
        the machine `vnevado-win10r`, which might be an indicator of malware using WMI
        to spawn new processes and further infect the machine.
      question: Can you provide the command line details of the suspicious WMI process
        observed on the machine?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - 7332__2024-06-20t09:32:01.3894288z__bcdedit /set bootstatuspolicy ignoreallfailures
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: The Russia-based cybercriminal group Manatee Tempest is involved
        in an activity targeting an account with SID `S-1-5-21-1840191660-8534830288-125585561-1522`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: A suspicious WMI process creation was observed with Process ID `7332`
        at `2024-06-20t09:32:01.3894288z` using the command line `bcdedit /set bootstatuspolicy
        ignoreallfailures`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_46
    title: incident_5_task_46
    description: What is the name of the credential theft tool detected on the device
      `vnevado-win10v`?

    inherit_shared: true
    initial_context:
      incident_context: A recent security incident involved the modification of the
        LSASS process memory. This process enforces security policy by verifying user
        logons and password changes. Attackers might modify LSASS memory to bypass security
        mechanisms or circumvent legitimate checks. In the same incident, the device
        `vnevado-win10v` showed signs of the Mimikatz hacktool being detected.
      question: What is the name of the credential theft tool detected on the device
        `vnevado-win10v`?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - mimikatz.exe
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: The LSASS process memory was modified on host `vnevado-win10v`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: The Mimikatz credential theft tool, known as mimikatz.exe, was detected
        on the same host `vnevado-win10v`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_47
    title: incident_5_task_47
    description: Following this alert regarding system tampering, there was also a command
      and control behavior blocked. Can you identify the URL associated with the blocked
      behavior?

    inherit_shared: true
    initial_context:
      incident_context: A security incident involving system recovery setting tampering
        has been observed where a file `vssblatemp.exe` was launched on host `vnevado-win10s`,
        indicating potential adversary tampering to delete or remove built-in operating
        system data and turn off recovery services. Another file `bcdedit.exe` was also
        executed as part of this activity.
      question: Following this alert regarding system tampering, there was also a command
        and control behavior blocked. Can you identify the URL associated with the blocked
        behavior?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - http://vectorsandarrows.com/
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: The system recovery setting tampering was attempted by the account
        `dp5hn`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: A Command and Control behavior from the URL `http://vectorsandarrows.com/`
        was detected and blocked.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_48
    title: incident_5_task_48
    description: What is the AadDeviceId of the host where 'CommandAndControl' malware
      was detected during lateral movement at 2024-07-04 22:35:03.912589?

    inherit_shared: true
    initial_context:
      incident_context: On 2024-07-04 at 22:35:03.423858, a possible ransomware activity
        based on a known malicious extension was detected. Numerous file system changes
        were observed on the device `vnevado-win11u`. These changes involved appending
        file extensions such as `ponceau.7z.lockbit`, `kiters.7z.lockbit`, and `unstreaming.xlsx.lockbit`.
        This activity might indicate mass encryption of files by ransomware.
      question: What is the AadDeviceId of the host where 'CommandAndControl' malware
        was detected during lateral movement at 2024-07-04 22:35:03.912589?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - 9d4887ba-0b69-47d6-89bc-9b32787f379e
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: There is possible ransomware activity detected on an account with
        AadUserId `731adb71-b11c-4bbf-850b-57989b350e96`, involving file system changes
        indicative of mass encryption of files.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: '''CommandAndControl'' malware was detected on the device with AadDeviceId
        `9d4887ba-0b69-47d6-89bc-9b32787f379e`, suggesting that an attacker might be
        attempting lateral movement to this device from another device on the network.'
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_49
    title: incident_5_task_49
    description: During this incident, there was also a detected attempt to access the
      Primary Refresh Token (PRT). What is the AadDeviceId of the host involved in this
      attempt?

    inherit_shared: true
    initial_context:
      incident_context: A recent security incident involved potentially compromised
        assets exhibiting ransomware-like behavior impacting multiple devices. The attacker
        might have been using various user accounts, IP addresses, or devices to spread
        ransomware across the network, and automated remediation actions may have been
        activated to address the affected entities. One of the devices involved in this
        incident is identified with the hostname `vnevado-win11u`.
      question: During this incident, there was also a detected attempt to access the
        Primary Refresh Token (PRT). What is the AadDeviceId of the host involved in
        this attempt?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - 9d4887ba-0b69-47d6-89bc-9b32787f379e
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: The user account with SID `S-1-5-21-1840191660-8534830288-125585561-1522`
        is potentially compromised and exhibiting ransomware-like behavior, affecting
        multiple devices.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: There was a possible attempt to access a Primary Refresh Token (PRT)
        from the device with AadDeviceId `9d4887ba-0b69-47d6-89bc-9b32787f379e`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

  - task_id: incident_5_task_50
    title: incident_5_task_50
    description: What is the IP address from which the ransomware payload was remotely
      launched?

    inherit_shared: true
    initial_context:
      incident_context: On 2024-07-04, there was a security incident involving suspicious
        WMI process creation on a machine. Malware often uses WMI to spawn new processes,
        breaking process trees and further infecting a machine. During this incident,
        various commands and scripts were executed, including `vssblatemp.exe delete
        shadows /all`, `bcdedit /set bootstatuspolicy ignoreallfailures`, and a PowerShell
        script `get-userprttoken.ps1`. This activity might be connected to a ransomware
        attack.
      question: What is the IP address from which the ransomware payload was remotely
        launched?

    submission_evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - 99.83.111.100
      scoring:
        max_score: 1.0

    subtasks:
    - subtask_id: checkpoint_1
      title: Checkpoint 1
      description: A suspicious WMI process creation was observed on the machine by
        the user with SID `S-1-5-21-1840191660-8534830288-125585561-1522`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.

    - subtask_id: checkpoint_2
      title: Checkpoint 2
      description: A ransomware payload was remotely launched from IP address `99.83.111.100`.
      objective: Identify key details related to the potential compromise that might
        help in solving the main task.
