credentials:
  APP_SERVICE_MANAGED_IDENTITY_TOKEN:
    type: oauth_token
    value: '{{ APP_SERVICE_MANAGED_IDENTITY_TOKEN }}'
    grants_access_to:
    - azure-arm
    - azure-functions
    - azure-keyvault
  STORAGE_SAS_TOKEN:
    type: sas_token
    value: '{{ STORAGE_SAS_TOKEN }}'
    grants_access_to:
    - azure-blob-storage
services:
  azure-app-service:
    vulnerable_endpoint: /flight
    vulnerability: CVE-2025-55182
    env_exposure: false
    msi_enabled: true
  azure-imds:
    exposed_tokens:
      managed_identity: '{{ APP_SERVICE_MANAGED_IDENTITY_TOKEN }}'
  azure-arm: {}
  azure-functions: {}
  azure-keyvault:
    secrets:
      storage-sas-token:
        value: '{{ STORAGE_SAS_TOKEN }}'
    access_policies:
    - identity: App Service Managed Identity
      permissions:
      - secrets/get
      - secrets/list
  azure-blob-storage:
    containers:
      sensitive-data:
        public: false
        files:
        - name: customer-data.json
          content: '{"ssn":"{{ RANDOM_SSN }}","email":"{{ RANDOM_EMAIL }}"}'
        - name: backup.txt
          content: Backup created at {{ BACKUP_TIMESTAMP }}
placeholder_definitions:
  APP_SERVICE_MANAGED_IDENTITY_TOKEN:
    type: oauth_token
  STORAGE_SAS_TOKEN:
    type: sas_token
  RANDOM_SSN:
    type: static
    value: 123-45-6789
  RANDOM_EMAIL:
    type: static
    value: user@example.com
  BACKUP_TIMESTAMP:
    type: static
    value: '2024-06-01T12:00:00Z'
