tasks:
  - task_id: incident_39_task_1
    title: incident_39_task_1
    description: "As part of this incident, a malicious credential theft tool execution was also detected. Can you identify the name of the credential theft tool that was executed?"

    inherit_shared: true

    initial_context:
      incident_context: "A security incident was detected where an attempt to disable the Microsoft Defender Antivirus service was reported. This is potentially an effort to evade detection. The tampering was detected at 2024-07-04 22:35:00.798303+00:00."
      question: "As part of this incident, a malicious credential theft tool execution was also detected. Can you identify the name of the credential theft tool that was executed?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "mimikatz.exe"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "An attempt to disable the Microsoft Defender Antivirus service was detected from the account with AadUserId `1d94aaf6-efe6-4e76-ad56-ffd7d1257bc1`"
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "The execution of a known malicious credential theft tool, `mimikatz.exe`, was detected."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_2
    title: incident_39_task_2
    description: "What is the name of the executable file that was involved in the remote file drop and potential human-operated malicious activity on `vnevado-win10b`?"

    inherit_shared: true

    initial_context:
      incident_context: "A remote file drop and execution incident was detected on host `vnevado-win10b`, involving an executable file launched from the system. The incident was associated with the account `fk8mq` (SID: S-1-5-21-1540151660-3530000288-105586595-1517, AadUserId: 97e6a954-b6bd-48a5-808c-bd8464cce677). The process execution details indicate it was run with specific command line parameters and originated from the IP address `141.216.110.153`. Related to this alert, there is also potential human-operated malicious activity on this device which might lead to ransomware or other payloads installed."
      question: "What is the name of the executable file that was involved in the remote file drop and potential human-operated malicious activity on `vnevado-win10b`?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "rubeus.exe"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "An attacker with AadUserId `97e6a954-b6bd-48a5-808c-bd8464cce677` remotely dropped and executed a file."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A file named `rubeus.exe` was involved in potential human-operated malicious activity that could lead to ransomware or other harmful payloads."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_3
    title: incident_39_task_3
    description: "What is the name of the account associated with the detection of a malicious credential theft tool execution on July 4th, 2024?"

    inherit_shared: true

    initial_context:
      incident_context: "On 2024-07-10, it was detected that emails containing a malicious URL were delivered and later removed. The emails had a specific sender IP and sender address and were associated with a person named Ethan Brooks, including his email and mailbox primary address details."
      question: "What is the name of the account associated with the detection of a malicious credential theft tool execution on July 4th, 2024?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "tgs2z"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The email account with SID `S-5-7-21-1843151660-3234030288-105586167-1422` received an email with a malicious URL, which was later removed."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "The account with the name `tgs2z` executed a known credential theft tool."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_4
    title: incident_39_task_4
    description: "Related to this alert, which process was responsible for the suspicious account creation?"

    inherit_shared: true

    initial_context:
      incident_context: "A security incident involved suspicious access to the LSASS service where attackers used tools to decrypt clear-text passwords from the LSASS service's memory. The activity occurred on a specific device identified by AadDeviceId, and one of the tools used was `mimikatz.exe`. This can be indicative of an attempt to obtain credentials for the purpose of lateral movement in the network."
      question: "Related to this alert, which process was responsible for the suspicious account creation?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "ProcessId 3624"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "There is suspicious access to the LSASS service on the host with AadDeviceId `4d8d23e9-a77d-4e33-9435-b8c457e57ca1`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A suspicious account was created using the command line `net.exe user /add bdadmin password1! /domain` on `2024-06-27t14:33:43.4299474z`, with Process ID `3624`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_5
    title: incident_39_task_5
    description: "Based on the latest alert related to this incident, can you determine the SID of the deceptive user account involved in the sign-in attempt?"

    inherit_shared: true

    initial_context:
      incident_context: "Recently, there was a suspected overpass-the-hash attack (Kerberos) involving the Helpdesk Administrator Emma Clark on VNEVADO-Win10V attempting to authenticate against VNEVADO-DC. The attack was part of a broader security incident where a file with suspicious attributes was registered as a service."
      question: "Based on the latest alert related to this incident, can you determine the SID of the deceptive user account involved in the sign-in attempt?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "S-0-6-5"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The account with AadUserId `97e6a954-b6bd-48a5-808c-bd8464cce677` belonging to Emma Clark (Helpdesk Administrator) on VNEVADO-Win10V attempted to authenticate against VNEVADO-DC, suspected of overpass-the-hash attack using Kerberos."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "A file with suspicious attributes was registered as a service on the host `vnevado-win10b`. An attacker might be attempting to establish persistence."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "A sign-in attempt was detected using a deceptive user account with SID `S-0-6-5`. The attacker might be using this fake or decoy account to perform further attacks."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_6
    title: incident_39_task_6
    description: "What is the name of the account observed to initiate suspicious remote activity on this machine?"

    inherit_shared: true

    initial_context:
      incident_context: "A malicious credential theft tool executed a command line indicating an intent to dump users' credentials. This was followed by the detection of multiple dual-purpose tools dropped on the device. These tools can be used for various malicious actions including credential theft, privilege escalation, and lateral movement."
      question: "What is the name of the account observed to initiate suspicious remote activity on this machine?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "LocalSystem"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A known credential theft tool execution command line was detected for the account with SID `S-5-7-21-1843151660-3234030288-105586167-1422`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "Multiple dual-purpose tools, including `psexesvc.exe`, were dropped on the device for potential malicious reasons."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "Suspicious remote activity was detected on the machine through the `LocalSystem` account."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_7
    title: incident_39_task_7
    description: "In the context of this incident, can you identify the name of the file that was associated with the anomalous account lookups?"

    inherit_shared: true

    initial_context:
      incident_context: "During a recent security incident, multiple alerts have indicated suspicious activity. On 2024-07-04 at 22:35:00.481750+00:00, a file named `psexesvc.exe` and a tool known as Rubeus were involved in an alert labeled 'Possible use of the Rubeus kerberoasting tool'. Following this, there was another related alert involving a host named `vnevado-win10b`."
      question: "In the context of this incident, can you identify the name of the file that was associated with the anomalous account lookups?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "domaindominance27.ps1"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The process `rubeus.exe` was detected, indicating the potential use of the Rubeus tool for kerberoasting or pass-the-ticket attacks."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "The host `vnevado-win10v` is associated with the use of the Rubeus kerberoasting tool, suggesting Kerberos authentication attacks on this endpoint."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "Anomalous account lookups were detected involving the file `domaindominance27.ps1`, indicating potential information gathering about targets."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_8
    title: incident_39_task_8
    description: "Given the recent incident, there was also an attempt to disable Microsoft Defender Antivirus service. Can you identify the account name associated with this suspicious activity?"

    inherit_shared: true

    initial_context:
      incident_context: "A security incident was detected involving a user named Ethan Brooks, who accessed a potentially malicious link in an email that was quarantined by zero-hour auto purge (ZAP). The accessed link was `https://ac27145722.livelygrass-8d4c4013.eastus2.azurecontainerapps.io/`. This alert was triggered based on a Microsoft Defender for Office 365 alert."
      question: "Given the recent incident, there was also an attempt to disable Microsoft Defender Antivirus service. Can you identify the account name associated with this suspicious activity?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "tgs2z"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "The user with AadUserId `1d94aaf6-efe6-4e76-ad56-ffd7d1257bc1` accessed a link in an email that was quarantined by zero-hour auto purge (ZAP)."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "There was an attempt to disable the Microsoft Defender Antivirus service by the account with Name `tgs2z`, indicating a possible attempt to evade detection."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_9
    title: incident_39_task_9
    description: "Considering another similar alert, can you provide the full command line associated with the process id 5196 that was detected for mimikatz.exe?"

    inherit_shared: true

    initial_context:
      incident_context: "A security incident involving the execution of a known malicious credential theft tool (mimikatz.exe) was detected. An instance of such execution was observed with the process id 6880 executing the command: `mimikatz.exe privilege::debug sekurlsa::pth /user:fk8mq /ntlm:96def1a633fc6790124d5f8fe21cc72b /domain:vnevado.alpineskihouse.co /run:\"powershell.exe dir \\vnevado-win10b\\c$\"`."
      question: "Considering another similar alert, can you provide the full command line associated with the process id 5196 that was detected for mimikatz.exe?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "\"mimikatz.exe\" privilege::debug sekurlsa::logonpasswords exit"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "A known credential theft tool `mimikatz.exe` was executed with the command line `mimikatz.exe privilege::debug sekurlsa::logonpasswords exit` at `2024-06-27t14:32:35.4061023z`, with Process ID `5196`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "The malicious credential theft tool was executed by the user with AadUserId `1d94aaf6-efe6-4e76-ad56-ffd7d1257bc1`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
  - task_id: incident_39_task_10
    title: incident_39_task_10
    description: "What is the Azure AD Device ID of the host where possible lateral movement was detected?"

    inherit_shared: true

    initial_context:
      incident_context: "As part of a recent security incident, Julian Burke, an IT director, had a Kerberos ticket used in a pass-the-ticket attack to access multiple resources and there were indications of lateral movement across devices."
      question: "What is the Azure AD Device ID of the host where possible lateral movement was detected?"

    evaluation_config:
      strategy: static
      criteria:
        expected_answers:
        - "fafdcd65-46c6-45a6-aa85-ec9b77ca0bcb"
      scoring:
        max_score: 1.0
    subtasks:
      - subtask_id: checkpoint_1
        title: Checkpoint 1
        description: "Julian Burke (IT director) on host `VNEVADO-Win10V` sent a replication request to `VNEVADO-DC`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_2
        title: Checkpoint 2
        description: "An actor took Julian Burke's Kerberos ticket and used it on host `VNEVADO-Win10V` to access 4 resources from IP address `35.202.74.47`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
      - subtask_id: checkpoint_3
        title: Checkpoint 3
        description: "There is a possible lateral movement involving device with AadDeviceId `fafdcd65-46c6-45a6-aa85-ec9b77ca0bcb`."
        objective: "Identify key details related to the potential compromise that might help in solving the main task."
