"""Log Aggregation Pattern (Internal Traffic Simulator)

Simulates benign service activity that would, in a real deployment, RESULT IN logs
being generated by the infrastructure services themselves. This component:
    • DOES NOT push logs or SecurityEvents directly to the SIEM.
    • Only makes lightweight service requests (or simulates them) to create natural noise.
    • Uses only standard logger debug output for developer observability.
"""

import asyncio
import logging
import random
from datetime import datetime, timedelta
from typing import Dict, Any, List

# Add shared utilities to path
import sys
sys.path.append('/app/shared')

# NOTE: Removed SIEM event schema imports since traffic simulators 
# should NOT log to SIEM directly


class LogAggregationPattern:
    """Simulates services sending logs to SIEM aggregator"""
    
    def __init__(self, http_client, scheduler):
        """Initialize the log aggregation pattern
        
        Args:
            http_client: InternalHTTPClient instance
            (event logger removed)
            scheduler: InternalPatternScheduler instance
        """
        self.http_client = http_client
    # event logger removed; use self.logger for debug only
        self.scheduler = scheduler
        self.logger = logging.getLogger(__name__)
        
        # Pattern configuration
        self.pattern_name = 'log_aggregation'
        self.interval_min = 25
        self.interval_max = 50
        
        # Statistics tracking
        self.stats = {
            'log_submissions': 0,
            'successful_submissions': 0,
            'failed_submissions': 0,
            'security_events_sent': 0,
            'access_logs_sent': 0,
            'error_logs_sent': 0,
            'metrics_sent': 0
        }
        
        # Log types and sources
        self.log_types = ['security_event', 'access_log', 'error_log', 'performance_metric']
        self.source_services = ['api_gateway', 'vault_service', 'webapp', 'database']
    
    async def run_pattern(self):
        """Main execution loop for log aggregation pattern"""
        self.logger.info(f"Starting {self.pattern_name} pattern")
        
        while self.scheduler.is_running():
            try:
                # Wait for next execution time
                await self._wait_for_next_execution()
                
                if not self.scheduler.is_running():
                    break
                
                # Execute log submission
                await self._execute_log_submission()
                
                # Occasionally submit batch of logs
                if random.random() < 0.12:  # 12% chance
                    await self._execute_batch_log_submission()
                
            except asyncio.CancelledError:
                self.logger.info(f"{self.pattern_name} pattern cancelled")
                break
            except Exception as e:
                self.logger.error(f"Error in {self.pattern_name} pattern: {e}")
                await asyncio.sleep(3)  # Brief pause on error
        
        self.logger.info(f"{self.pattern_name} pattern completed")
    
    async def _wait_for_next_execution(self):
        """Wait for the next pattern execution with jitter"""
        interval = random.uniform(self.interval_min, self.interval_max)
        
        # Add small jitter for realistic timing
        jitter = random.uniform(-2, 2)
        wait_time = max(5, interval + jitter)  # Minimum 5 second wait
        
        await asyncio.sleep(wait_time)
    
    async def _execute_log_submission(self):
        """Execute a single log submission to SIEM aggregator"""
        log_type = random.choice(self.log_types)
        source_service = random.choice(self.source_services)
        
        self.logger.info(f"Submitting {log_type} from {source_service} to SIEM")
        
        try:
            # Generate realistic log data
            log_data = self._generate_log_data(log_type, source_service)
            
            # Make HTTP request to infrastructure service instead of logging to SIEM
            # The infrastructure service will handle SIEM logging
            result = await self._make_service_request(source_service, log_data)
            
            self.stats['log_submissions'] += 1
            
            if result.get('status_code', 500) < 400:
                self.stats['successful_submissions'] += 1
                self._update_log_type_stats(log_type)
                self.logger.debug(f"Log submission successful: {log_type} from {source_service}")
            else:
                self.stats['failed_submissions'] += 1
                self.logger.warning(f"Log submission failed: {log_type} from {source_service}")
            
            # Log security event for log aggregation (meta-logging)
            await self._log_aggregation_event(log_type, source_service, result)
            
        except Exception as e:
            self.stats['failed_submissions'] += 1
            self.logger.error(f"Log submission exception: {e}")
    
    async def _execute_batch_log_submission(self):
        """Execute batch submission of multiple logs"""
        self.logger.info("Executing batch log submission")
        
        batch_size = random.randint(3, 7)
        
        for _ in range(batch_size):
            try:
                log_type = random.choice(self.log_types)
                source_service = random.choice(self.source_services)
                
                log_data = self._generate_log_data(log_type, source_service)
                # Make HTTP request to infrastructure service instead of logging to SIEM
                result = await self._make_service_request(source_service, log_data)
                
                self.stats['log_submissions'] += 1
                
                if result.get('status_code', 500) < 400:
                    self.stats['successful_submissions'] += 1
                    self._update_log_type_stats(log_type)
                else:
                    self.stats['failed_submissions'] += 1
                
                # Log the batch submission event
                await self._log_aggregation_event(log_type, source_service, result, is_batch=True)
                
                # Brief delay between batch submissions
                await asyncio.sleep(random.uniform(0.2, 0.5))
                
            except Exception as e:
                self.stats['failed_submissions'] += 1
                self.logger.error(f"Batch log submission failed: {e}")
    
    def _generate_log_data(self, log_type: str, source_service: str) -> Dict[str, Any]:
        """Generate realistic log data based on type and source"""
        base_timestamp = datetime.utcnow() - timedelta(seconds=random.randint(1, 300))
        
        base_data = {
            'timestamp': base_timestamp.isoformat(),
            'source_service': source_service,
            'log_type': log_type,
            'log_level': self._get_realistic_log_level(log_type),
            'internal_traffic': True
        }
        
        if log_type == 'security_event':
            base_data.update(self._generate_security_event_data(source_service))
        elif log_type == 'access_log':
            base_data.update(self._generate_access_log_data(source_service))
        elif log_type == 'error_log':
            base_data.update(self._generate_error_log_data(source_service))
        else:  # performance_metric
            base_data.update(self._generate_performance_metric_data(source_service))
        
        return base_data
    
    def _generate_security_event_data(self, source_service: str) -> Dict[str, Any]:
        """Generate security event log data"""
        events = [
            'user_authentication_success',
            'token_validation_success', 
            'secret_access_authorized',
            'configuration_retrieved',
            'health_check_completed'
        ]
        
        return {
            'event_type': random.choice(events),
            'user_id': f'service_{source_service}',
            'ip_address': f'172.20.0.{random.randint(10, 50)}',
            'status': 'success',
            'details': f'Internal {source_service} operation completed successfully'
        }
    
    def _generate_access_log_data(self, source_service: str) -> Dict[str, Any]:
        """Generate access log data"""
        endpoints = {
            'api_gateway': ['/health', '/api/services'],
            'vault_service': ['/health', '/secrets/status', '/secrets/list'],
            'webapp': ['/admin/dashboard', '/api/users', '/admin/logs'],
            'database': ['/status', '/metrics', '/health']
        }
        
        service_endpoints = endpoints.get(source_service, ['/health'])
        
        return {
            'method': random.choice(['GET', 'POST']),
            'endpoint': random.choice(service_endpoints),
            'status_code': random.choices([200, 201, 304], weights=[0.8, 0.1, 0.1])[0],
            'response_time_ms': random.randint(10, 500),
            'user_agent': f'Internal-Service-{source_service}/1.0'
        }
    
    def _generate_error_log_data(self, source_service: str) -> Dict[str, Any]:
        """Generate error log data"""
        error_types = [
            'temporary_connection_timeout',
            'configuration_warning',
            'rate_limit_approached',
            'cache_miss_warning',
            'retry_attempt_logged'
        ]
        
        return {
            'error_type': random.choice(error_types),
            'error_code': f'WARN_{random.randint(1000, 9999)}',
            'message': f'Non-critical {random.choice(error_types).replace("_", " ")} in {source_service}',
            'stack_trace': None,  # Internal warnings don't usually have stack traces
            'recoverable': True
        }
    
    def _generate_performance_metric_data(self, source_service: str) -> Dict[str, Any]:
        """Generate performance metrics data"""
        return {
            'metric_name': f'{source_service}_performance',
            'cpu_usage_percent': round(random.uniform(5, 30), 2),
            'memory_usage_mb': random.randint(50, 200),
            'request_count_per_minute': random.randint(20, 100),
            'average_response_time_ms': random.randint(15, 300),
            'active_connections': random.randint(5, 25)
        }
    
    def _get_realistic_log_level(self, log_type: str) -> str:
        """Get realistic log level for given log type"""
        level_weights = {
            'security_event': {'INFO': 0.7, 'WARN': 0.2, 'ERROR': 0.1},
            'access_log': {'INFO': 0.9, 'WARN': 0.08, 'ERROR': 0.02},
            'error_log': {'WARN': 0.6, 'ERROR': 0.3, 'CRITICAL': 0.1},
            'performance_metric': {'INFO': 0.8, 'WARN': 0.15, 'ERROR': 0.05}
        }
        
        weights = level_weights.get(log_type, {'INFO': 1.0})
        levels = list(weights.keys())
        probabilities = list(weights.values())
        
        return random.choices(levels, weights=probabilities)[0]
    
    def _update_log_type_stats(self, log_type: str):
        """Update statistics for specific log type"""
        if log_type == 'security_event':
            self.stats['security_events_sent'] += 1
        elif log_type == 'access_log':
            self.stats['access_logs_sent'] += 1
        elif log_type == 'error_log':
            self.stats['error_logs_sent'] += 1
        elif log_type == 'performance_metric':
            self.stats['metrics_sent'] += 1
    
    async def _log_aggregation_event(self, log_type: str, source_service: str, result: Dict[str, Any], is_batch: bool = False):
        """Log the aggregation event locally (for debugging)"""
        status_code = result.get('status_code', 500)
        success = status_code < 400
        
        # Use local event logger for debugging only
        self.logger.debug(
            "log_aggregation_request",
            extra={
                'source_service': source_service,
                'target_service': 'infrastructure',
                'status': 'success' if success else 'failure',
                'log_type': log_type,
                'status_code': status_code,
                'is_batch_submission': is_batch
            }
        )
    
    async def _make_service_request(self, source_service: str, log_data: Dict[str, Any]) -> Dict[str, Any]:
        """Make HTTP request to infrastructure service instead of direct SIEM logging
        
        Traffic simulators should make HTTP requests to infrastructure services,
        which then handle SIEM logging internally.
        """
        try:
            # Map service names to appropriate endpoints
            if source_service == 'api_gateway':
                return await self.http_client.api_gateway_request('/health')
            elif source_service == 'vault_service':
                return await self.http_client.vault_request('/health', method='GET')
            elif source_service == 'webapp':
                # Make basic request to webapp (without uploading files)
                return {'status_code': 200, 'message': 'webapp request simulated'}
            elif source_service == 'database':
                # Database is not directly accessible via HTTP, simulate success
                return {'status_code': 200, 'message': 'database request simulated'}
            else:
                return {'status_code': 200, 'message': f'{source_service} request simulated'}
        except Exception as e:
            self.logger.error(f"Service request failed: {e}")
            return {'error': str(e), 'status_code': 500}
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get pattern execution statistics"""
        success_rate = 0
        if self.stats['log_submissions'] > 0:
            success_rate = (self.stats['successful_submissions'] / self.stats['log_submissions']) * 100
        
        return {
            'pattern_name': self.pattern_name,
            'log_submissions': self.stats['log_submissions'],
            'successful_submissions': self.stats['successful_submissions'],
            'failed_submissions': self.stats['failed_submissions'],
            'success_rate_percent': round(success_rate, 2),
            'security_events_sent': self.stats['security_events_sent'],
            'access_logs_sent': self.stats['access_logs_sent'],
            'error_logs_sent': self.stats['error_logs_sent'],
            'metrics_sent': self.stats['metrics_sent']
        }