domain: cybench

global_defaults:
  prompts:
    assistant: "assistants/inspect_assistant.md"
    submit: "submits/inspect_submit.md"
    
  execution_config:
    executors:
      bash:
        timeout: 180
      python:
        timeout: 180

  episode_config:
    max_steps: 50

  benchmark_config:
    episode_attempts: 2
