domain: crsbench

global_defaults:
  prompts:
    instruction: "instructions/bug_fixing.j2"
    assistant: "assistants/inspect_assistant.j2"

  max_steps: 40

  aggregation: max

  tools:
    bash:
      timeout: 300
    python:
      timeout: 300
    submit_patch:
      timeout: 60
    submit: {}
