domain: cybench

global_defaults:
  prompts:
    assistant: "assistants/inspect_assistant.j2"
    submit: "submits/inspect_submit.j2"
    continue: "continues/inspect_continue.j2"

  max_steps: 30

  aggregation: max
