domain: excytin

global_defaults:
  default_dataset: latest_test_set

  permanent_environment:
    name: "excytin-databases"
    compose: "compose/all_incidents.compose.yml"

  prompts:
    instruction: "instructions/excytin_demo.md"
    assistant: "assistants/inspect_assistant.md"

  max_steps: 25

  aggregation: max

  tools:
    bash:
      timeout: 180
    python:
      timeout: 180
